### PR TITLE
Reset elements to original position

### PR DESCRIPTION
**Pull request by kukiron**
Hi, 

First of all, thanks for this fun library. 

This PR provides the option to pause the music & set elements to the original state (with "Pause Demo", instead of "Stop Demo") & then restart from there.

Also, an option for "Reset" from the beginning.

### CODE REVIEW

**Comment by Okazari** [comment]
Hi ! Thanks for the contribution.

Sorry, I may have not explain myself enought on this issue. I was considering adding this into the library itself, not only for the demo page ;)

This would required some changes : 
 - A way to provide the option or a "stopAndReset" function
 - Each dance would need a reset function that could be called to reset elements.

Not sure atm how to do it properly.

**Comment by kukiron** [comment]
Sorry, I misunderstood!

Will look into this.

Thanks for the feedback

**Comment by Okazari** [comment]
That's also my bad, feel free to ask if you have any question

**Comment by nesvand** [comment]
I've opened pull request #54 to resolve #38 based on the comments provided here

**Comment by Okazari** [comment]
Sorry but this is done in #54. Thanks for your time invested anyway !

**Pull request closed without merging**
