### PR TITLE
introducing the letter-spacing dance !

### PR DESCRIPTION
**Pull request by mathieu-pousse**
kern me I'm famous !

### CODE REVIEW

**Comment by Okazari** [comment]
Can you explain the "Kern" name ? 😋

**Comment by mathieu-pousse** [comment]
check it out https://en.wikipedia.org/wiki/Kerning

This is the scientific word for "letter-spacing"

**Comment by Okazari** [comment]
kern-rythm

**Comment by Okazari** [comment]
kern-rythm

**Pull request merged**
