### PR TITLE
Translate README.md to Korean

### PR DESCRIPTION
**Pull request by tnwjd4623**
I translate README.md file to Korean. 
File name is README_KR.md

### CODE REVIEW

**Comment by Okazari** [comment]
Why did you close the Pull request ? :'(

**Comment by tnwjd4623** [comment]
I think there were so many commits in this branch TT. I will send new pull-request with readme only :) !

**Comment by tnwjd4623** [comment]
> Why did you close the Pull request ? :'(
I think there were so many commits in this branch TT. I will send new pull-request with readme only :) !

**Comment by Okazari** [comment]
Great ! Looking forward for your next PR then :)
I'm working on a release this week and your dance is included ;)

**Pull request closed without merging**
